name: poc_endgame_animation
author: Kstars_
version: '1.0.4-POC'
main: fr.kstars.poc_endgame_animation.Main
api-version: '1.21'
softdepend:
  - Citizens
  - ProtocolLib
commands:
  endgame_animation:
    description: Start the endgame animation