name: pocEndgameAnimation
author: Kstars_
version: '1.0.7-POC'
main: fr.kstars.pocEndgameAnimation.Main
api-version: '1.21'
softdepend:
  - Citizens
  - ProtocolLib
commands:
  endgame_animation:
    description: Start the endgame animation